config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get "login",  to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
  end

  resources :products

  resources :categories
  resources :users

  root 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :products

  validates :name, uniqueness: true, presence: true
end

app/models/category/searcher.rb
class Category::Searcher

  class << self
    def search(params)
      params ||= {}
      params   = params.with_indifferent_access

      params[:query] ? Category.where(search_query, query: "%#{params[:query]}%") : Category.all
    end

    private

    def search_query
      'categories.name ILIKE :query'
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :categories

  mount_uploader :picture, PictureUploader

  validates_presence_of :name, :price
  validates_numericality_of :price
end

app/models/product/searcher.rb
class Product::Searcher

  class << self
    def search(params)
      params ||= {}
      params   = params.with_indifferent_access

      query    = params[:query]
      category = params[:category]

      results  = category ? Product.joins(:categories).references(:categories).where(categories: { name: category }) : Product.all
      results  = results.where(search_query, query: "%#{query}%") if query
      results
    end

    private

    def search_query
      'products.name ILIKE :query OR description ILIKE :query'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :rememberable, 
  # :recoverable, :registerable and :omniauthable
  devise :database_authenticatable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  
  helper_method :sort_column, :sort_direction

  private

  # helper methods for index page sorting
  def sort_column
    model_name  = controller_name.classify
    model_name.constantize.column_names.include?(params[:sort]) ? params[:sort] : 'id'
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category::Searcher.search(params[:search]).
                    order(sort_column + " " + sort_direction).
                    page(params[:page]).per(10)
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit]

  # GET /products
  def index
    table_name = controller_name.classify.pluralize.downcase #to avoid ambigous column name
    
    @products = Product::Searcher.search(params[:search]).
                  order("#{table_name}.#{sort_column} #{sort_direction}").
                  page(params[:page]).per(10)
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def product_params
    params.require(:product).permit(:name, :price, :description, :picture, category_ids: [])
  end

  def set_categories
    @categories = Category.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    @column = column

    link_to title, params.merge(:sort => column, :direction => direction, :page => nil, remote: true), 
      { :class => css_class }
  end

  private
  attr_reader :column

  # css class for sorting arrow
  def css_class
    column.downcase == sort_column.downcase ? (css_chevron + '-' + sort_html_class(sort_direction)) : nil
  end

  def css_chevron
    'glyphicon glyphicon-chevron'
  end

  # css class for sorting arrow direction
  def sort_html_class(direction)
    direction == 'asc' ? 'up' : 'down'
  end

  def direction
    column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_categories.html.haml
= hidden_field_tag :direction, params[:direction]
= hidden_field_tag :sort,      params[:sort]

= paginate @categories

%table.table.table-striped
  %thead
    %tr
      %th= sortable 'id'
      %th= sortable 'name'
      %th
  %tbody
    - @categories.each do |category|
      %tr
        %td= link_to category.id, category_path(category)
        %td= category.name
        %td
          = link_to 'Edit', edit_category_path(category), :class => 'btn btn-default btn-xs'
          = link_to 'Destroy', category_path(category), :method => :delete, :data => { confirm: 'Are you sure?' }, :class => 'btn btn-xs btn-danger'

= paginate @categories, :remote => true

app/views/categories/_form.html.haml
= form_for @category, html: { class: "form form-horizontal category" } do |f|
  - if @category.errors.any?
    .alert.alert-danger
      - @category.errors.full_messages.each do |msg|
        %li= msg

  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@category[:name])
  
  = f.submit nil,class: 'btn btn-primary'
  = link_to 'Cancel', categories_path, :class => 'btn btn-default'

app/views/categories/edit.html.haml
.page-header
  %h1 Edit Category
= render :partial => "form"

app/views/categories/index.html.haml
.page-header
  %h1 Categories

= render 'partials/search'
  
#categories
  = render 'categories'

%p= link_to 'New', new_category_path, :class => 'btn btn-primary'

app/views/categories/index.js.haml
$("#categories").html("#{escape_javascript(render('categories'))}");

app/views/categories/new.html.haml
.page-header
  %h1 Create Category
= render :partial => "form"

app/views/categories/show.html.haml
.page-header
  %h1= Category

%p
  %strong= 'Name:'
  %br
  = @category.name


= link_to 'Back',    categories_path, :class => 'btn btn-default'
= link_to 'Edit',    edit_category_path(@category), :class => 'btn btn-default'
= link_to 'Destroy', category_path(@category), :method => "delete", :data => { confirm: 'Are you sure?' }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Warehouse
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .container
      .col-md-3
        .left-navigation
          = render_navigation :renderer => :bootstrap
      .col-md-9
        = yield

app/views/partials/_search.html.haml
= form_tag({}, method: :get, id: :search, remote: true) do
  %p
    = text_field_tag 'search[query]', params[:search]
    = submit_tag "Search", name: nil

app/views/products/_form.html.haml
= form_for @product, html: { class: "form form-horizontal product", multiple: true } do |f|
  - if @product.errors.any?
    .alert.alert-danger
      - @product.errors.full_messages.each do |msg|
        %li= msg

  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@product[:name])
  
  .form-group
    = f.label :price, class: 'control-label'
    .controls
      = f.number_field :price, class: 'form-control', required: true
    = error_span(@product[:price])
  
  .form-group
    = f.label :description, class: 'control-label'
    .controls
      = f.text_field :description, class: 'form-control'
    = error_span(@product[:description])
  
  .form-group
    = f.label :categories, class: 'control-label'
    .controls
      = select_tag 'product[category_ids]', options_from_collection_for_select(@categories, :id, :name, @product.categories.map(&:id)), multiple: true, class: 'selectpicker'
  
  .form-group
    = f.label :picture, class: 'control-label'
    .controls
      = f.file_field :picture, class: 'form-control'
      = f.hidden_field :picture_cache
    = error_span(@product[:picture])
  
  = f.submit nil,class: 'btn btn-primary'
  = link_to 'Cancel', products_path, :class => 'btn btn-default'

app/views/products/_products.html.haml
= hidden_field_tag :direction, params[:direction]
= hidden_field_tag :sort, params[:sort]

= paginate @products, :remote => true

%table.table.table-striped
  %thead
    %tr
      %th= sortable 'id'
      %th Picture
      %th= sortable 'name'
      %th Price
      %th Description
      %th Categories
      %th
  %tbody
    - @products.each do |product|
      %tr
        %td= link_to product.id, product_path(product)
        %td= image_tag product.picture.thumb.url
        %td= product.name
        %td= product.price
        %td= product.description
        %td
          - product.categories.each do |cat|
            =link_to cat.name, params.merge( search: { category: cat.name } ), remote: true
        %td
          = link_to 'Edit', edit_product_path(product), :class => 'btn btn-default btn-xs'
          = link_to 'Destroy', product_path(product), :method => :delete, :data => { confirm: 'Are you sure?' }, :class => 'btn btn-xs btn-danger'

= paginate @products, :remote => true

app/views/products/edit.html.haml
.page-header
  %h1 Edit Product
= render :partial => "form"

app/views/products/index.html.haml
.page-header
  %h1 Products

= render 'partials/search'

#products
  = render 'products'

%p= link_to 'New', new_product_path, :class => 'btn btn-primary'

app/views/products/index.js.haml
$("#products").html("#{escape_javascript(render('products'))}");

app/views/products/new.html.haml
.page-header
  %h1 New Product
= render :partial => "form"

app/views/products/show.html.haml
.page-header
  %h1 Product

%p
  %strong Name:
  %br
  = @product.name
%p
  = image_tag @product.picture_url
%p
  %strong Price: 
  %br
  = @product.price
%p
  %strong Description:
  %br
  = @product.description
%p
  %strong Categories
  %br
  = @product.categories.map(&:name).join(', ')


= link_to 'Back',    products_path, :class => 'btn btn-default'
= link_to 'Edit',    edit_product_path(@product), :class => 'btn btn-default'
= link_to 'Destroy', product_path(@product), :method => "delete", :data => { confirm: 'Are you sure?' }, :class => 'btn btn-danger'

app/views/users/_form.html.haml
= form_for @user, html: { class: "form form-horizontal category" } do |f|
  - if @user.errors.any?
    .alert.alert-danger
      - @user.errors.full_messages.each do |msg|
        %li= msg
  .form-group
    = f.label :email, class: 'control-label'
    .controls
      = f.text_field :email, class: 'form-control', required: true
  .form-group
    = f.label :password, class: 'control-label'
    .controls
      = f.password_field :password, class: 'form-control', required: true
  
  = f.submit nil,class: 'btn btn-primary'
  = link_to 'Cancel', users_path, :class => 'btn btn-default'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

app/views/users/index.html.haml
%h1 Listing users

%table.table.table-striped
  %thead
    %tr
      %th Id
      %th Email
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %th= link_to user.id, user
        %th= user.email
        %td= link_to 'Edit', edit_user_path(user), :class => 'btn btn-default btn-xs'
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-xs btn-danger'

%br

= link_to 'New User', new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
%h1 New user
= render 'form'

app/views/users/show.html.haml
.page-header
  %h1= User

%p
  %strong= 'Email:'
  %br
  = @user.email


= link_to 'Back',    users_path, :class => 'btn btn-default'
= link_to 'Edit',    edit_user_path(@user), :class => 'btn btn-default'
= link_to 'Destroy', user_path(@user), :method => "delete", :data => { confirm: 'Are you sure?' }, :class => 'btn btn-danger'